# Generated by Django 2.2 on 2021-07-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Set_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('flavor_text', models.CharField(max_length=450)),
                ('small', models.URLField()),
                ('normal', models.URLField()),
                ('large', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Artist')),
                ('digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Digital')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Rarity')),
            ],
        ),
    ]
