# Generated by Django 2.2 on 2021-07-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='oracle_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='set_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Set_name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
