# Generated by Django 2.2 on 2021-07-31 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Legalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Mana_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mana_cost', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toughness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toughness', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='oracle_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='set_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Set_name'),
        ),
        migrations.AddField(
            model_name='card',
            name='type_line',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal', models.BooleanField(null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legals', to='card_search.Card')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legals', to='card_search.Legalities')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=45)),
                ('cards', models.ManyToManyField(related_name='keywords', to='card_search.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1)),
                ('cards', models.ManyToManyField(related_name='colors', to='card_search.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Color_identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_iden', models.CharField(max_length=1)),
                ('cards', models.ManyToManyField(related_name='color_idens', to='card_search.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Card_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=45)),
                ('cards', models.ManyToManyField(related_name='card_types', to='card_search.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cmc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Cmc'),
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Layout'),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Mana_cost'),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Power'),
        ),
        migrations.AddField(
            model_name='card',
            name='toughness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Toughness'),
        ),
    ]
