# Generated by Django 2.2 on 2021-07-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0002_auto_20210725_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toughness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toughness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1)),
                ('cards', models.ManyToManyField(related_name='cards', to='card_search.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Power'),
        ),
        migrations.AddField(
            model_name='card',
            name='toughness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Toughness'),
        ),
    ]
