# Generated by Django 2.2 on 2021-11-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0003_auto_20211112_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='card',
        ),
        migrations.AddField(
            model_name='legal',
            name='card',
            field=models.ManyToManyField(null=True, related_name='legals', to='card_search.Card'),
        ),
    ]
