# Generated by Django 2.2 on 2021-07-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0003_auto_20210726_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='cards',
            field=models.ManyToManyField(related_name='colors', to='card_search.Card'),
        ),
        migrations.CreateModel(
            name='Color_identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_iden', models.CharField(max_length=1)),
                ('cards', models.ManyToManyField(related_name='color_idens', to='card_search.Card')),
            ],
        ),
    ]
