# Generated by Django 2.2 on 2021-07-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0004_auto_20210726_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=45)),
                ('cards', models.ManyToManyField(related_name='keywords', to='card_search.Card')),
            ],
        ),
    ]
