# Generated by Django 2.2 on 2021-11-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0004_auto_20211121_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legal',
            old_name='card',
            new_name='cards',
        ),
    ]
