# Generated by Django 2.2 on 2021-07-27 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0005_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Card_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=45)),
                ('cards', models.ManyToManyField(related_name='card_types', to='card_search.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Layout'),
        ),
    ]
