# Generated by Django 2.2 on 2021-11-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0005_auto_20211122_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='name',
        ),
        migrations.AddField(
            model_name='legal',
            name='name',
            field=models.ManyToManyField(null=True, related_name='legalities', to='card_search.Legalities'),
        ),
    ]
