# Generated by Django 2.2 on 2021-11-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0006_auto_20211124_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='cards',
            field=models.ManyToManyField(related_name='legals', to='card_search.Card'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='name',
            field=models.ManyToManyField(related_name='legalities', to='card_search.Legalities'),
        ),
    ]
