# Generated by Django 2.2 on 2021-07-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0007_auto_20210727_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('legal', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='legalities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.Legal'),
        ),
    ]
