# Generated by Django 2.2 on 2021-11-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0007_auto_20211124_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='cards',
        ),
        migrations.AddField(
            model_name='legal',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_cards', to='card_search.Card'),
        ),
        migrations.AddField(
            model_name='legalities',
            name='cards',
            field=models.ManyToManyField(null=True, through='card_search.Legal', to='card_search.Card'),
        ),
        migrations.RemoveField(
            model_name='legal',
            name='name',
        ),
        migrations.AddField(
            model_name='legal',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='format', to='card_search.Legalities'),
        ),
    ]
