# Generated by Django 2.2 on 2021-07-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0008_auto_20210728_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='legal',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legals', to='card_search.Legalities'),
        ),
    ]
