# Generated by Django 2.2 on 2021-07-30 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_search', '0009_auto_20210729_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='legalities',
        ),
        migrations.AddField(
            model_name='legal',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legals', to='card_search.Card'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='legal',
            field=models.BooleanField(null=True),
        ),
    ]
